//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TASKEntities : DbContext
    {
        public TASKEntities()
            : base("name=TASKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device_Categories> Device_Categories { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Property_Items> Property_Items { get; set; }
        public virtual DbSet<Property_Options> Property_Options { get; set; }
        public virtual DbSet<Property_Value> Property_Value { get; set; }
        public virtual DbSet<Property_Value_Option> Property_Value_Option { get; set; }
    }
}
